config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end

  get 'articles/:id/like' => 'articles#like'
  get 'articles/:article_id/comments/:id/like' => 'comments#like'

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  validates :title, presence: true,
            length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "alsan", password: "alsan", except: [:index, :show, :like]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    uploaded_io = params[:article][:image]
    name = Time.now.to_i.to_s + uploaded_io.original_filename
    File.open(Rails.root.join('public', 'images', name), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    @article.img = name

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    uploaded_io = params[:article][:image]
    name = Time.now.to_i.to_s + uploaded_io.original_filename
    File.open(Rails.root.join('public', 'images', name), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    @article.img = name

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  def like
    if session[:likes].nil?
      session[:likes] = []
    end
    @article = Article.find(params[:id])
    if session[:likes].include? params[:id]
      @article.likes -= 1
      session[:likes].delete(params[:id])
    else
      session[:likes] << params[:id]
      if @article.likes.nil?
        @article.likes = 1
      else
        @article.likes += 1
      end
    end




    @article.save
    redirect_to @article
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "alsan", password: "alsan", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  def like
    if session[:comments].nil?
      session[:comments] = []
    end
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    if session[:comments].include? params[:id]
      @comment.likes -= 1
      session[:comments].delete(params[:id])
    else
      session[:comments] << params[:id]
      if @comment.likes.nil?
        @comment.likes = 1
      else
        @comment.likes += 1
      end
    end
    @comment.save
    redirect_to @article
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <%= f.file_field :image %>

    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>
<br><br>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Likes</th>
    <th>Actions</th>
  </tr>

  <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= article.likes %></td>
        <td>
          <%= link_to 'Show', article_path(article) %>
          <%= link_to 'Edit', edit_article_path(article) %>
          <%= link_to 'Destroy', article_path(article),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<img src="<%= image_url(@article.img) %>" style="max-height: 300px">
<br>
<% if session[:likes] and session[:likes].include? params[:id] %>
  <%= link_to 'UnLike', article_path(@article) + '/like/' %> <%= @article.likes %>
<% else  %>
    <%= link_to 'Like', article_path(@article) + '/like/' %> <%= @article.likes %>
<% end %>
<br>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <% if session[:comments] and session[:comments].include? comment.id.to_s %>
    <%= link_to 'UnLike', article_comment_path(comment.article, comment) + '/like/' %> <%= comment.likes %>
  <% else %>
    <%= link_to 'Like', article_comment_path(comment.article, comment) + '/like/' %> <%= comment.likes %>
  <% end %>
  |
  <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>
<hr>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>